version: "3"

#This is for development only and NOT used for deployment
services:
  database:
    ports:
      - 8000:5432
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=$DATABASE
      - POSTGRES_USER=$USER
      - POSTGRES_PASSWORD=$PASSWORD
  pgweb:
    ports:
      - 8001:8081
    image: sosedoff/pgweb
    restart: always
    environment:
    - DATABASE_URL=postgres://$USER:$PASSWORD@database:5432/$DATABASE?sslmode=disable